In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df= pd.read_csv("/content/IMDB Dataset.csv")

In [22]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [23]:
df.shape

(50000, 2)

In [24]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [26]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [27]:
df.duplicated().sum() #checking duplicated rows

np.int64(418)

In [28]:
df= df.drop_duplicates() #removes the duplicate rows

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.shape

(49582, 2)

In [31]:
df['sentiment'].value_counts()

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [32]:
#convert the categorical target variable into numerical

df["sentiment"] = df["sentiment"].map({"negative" :0, "positive":1})

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49582 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     49582 non-null  object
 1   sentiment  49582 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.1+ MB

In [34]:
#TEXT PRE-PROCESSING
#CONVERTING INTO LOWER CASE

df["review"]= df["review"].str.lower()

In [35]:
df.head()

                                              review  sentiment
0  one of the other reviewers has mentioned that ...          1
1  a wonderful little production. <br /><br />the...          1
2  i thought this was a wonderful way to spend ti...          1
3  basically there's a family where a little boy ...          0
4  petter mattei's "love in the time of money" is...          1

In [36]:
#removing any punctuation marks

import string
def remove_punc(txt):
  return txt.translate(str.maketrans('', '', string.punctuation))

In [38]:
df['review']= df['review'].apply(remove_punc)

In [39]:
df.head()

                                              review  sentiment
0  one of the other reviewers has mentioned that ...          1
1  a wonderful little production br br the filmin...          1
2  i thought this was a wonderful way to spend ti...          1
3  basically theres a family where a little boy j...          0
4  petter matteis love in the time of money is a ...          1

In [41]:
import nltk #natural language tool kit library

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [42]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [43]:
stop_words = set(stopwords.words('english')) #creating a list of stopwords

In [44]:
#its always better not to remove the negative words to know the emotion
stop_words.discard("not")
stop_words.discard("no")
stop_words.discard("nor")

In [45]:
df.loc[1]['review']

'a wonderful little production br br the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life br br the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [46]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if i not in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [47]:
df['review']= df['review'].apply(remove)

In [48]:
df.loc[1]['review']

'wonderful little production br br filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece br br actors extremely well chosen michael sheen not got polari voices pat truly see seamless editing guided references williams diary entries not well worth watching terrificly written performed piece masterful production one great masters comedy life br br realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [53]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['review'] = df['review'].apply(remove_numbers)

In [54]:
def tokenize_text(txt):
  tokens=txt.split()
  return tokens

In [55]:
df['tokens']= df['review'].apply(tokenize_text)

In [56]:
df[["review","tokens"]].head()

,review,tokens
0,one reviewers mentioned watching oz episode y...,"[one, reviewers, mentioned, watching, oz, epis..."
1,wonderful little production br br filming tech...,"[wonderful, little, production, br, br, filmin..."
2,thought wonderful way spend time hot summer we...,"[thought, wonderful, way, spend, time, hot, su..."
3,basically theres family little boy jake thinks...,"[basically, theres, family, little, boy, jake,..."
4,petter matteis love time money visually stunni...,"[petter, matteis, love, time, money, visually,..."

In [62]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [63]:
lemmatizer = WordNetLemmatizer()

In [64]:
def lemmatize_text(tokens):
    lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]
    return " ".join(lemmatized_words)

In [65]:
df["cleaned_review"] = df["tokens"].apply(lemmatize_text)

In [66]:
print(df["cleaned_review"].iloc[0])

one reviewer mentioned watching oz episode youll hooked right exactly happened mebr br first thing struck oz brutality unflinching scene violence set right word go trust not show faint hearted timid show pull no punch regard drug sex violence hardcore classic use wordbr br called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy not high agenda em city home manyaryans muslim gangsta latino christian italian irish moreso scuffle death stare dodgy dealing shady agreement never far awaybr br would say main appeal show due fact go show wouldnt dare forget pretty picture painted mainstream audience forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste oz got accustomed high level graphic violence not violence injustice crooked guard wholl sold nickel inmate wholl kill order get away well mannered middle class inmate turned prison bitch due lack street skill prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side

In [68]:
X= df['cleaned_review']
y= df['sentiment']

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

In [71]:
#we should split the data before bag of words to avoid data leakage
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify=y)

In [72]:
#BAG OF WORDS
from sklearn.feature_extraction.text import CountVectorizer

In [75]:
bow = CountVectorizer(max_features = 5000) #keeps only 5000 common words; this makes model fast and simple

In [77]:
X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [78]:
#create the model
log_model = LogisticRegression(max_iter= 1000)

In [80]:
#train the data
log_model.fit(X_train_bow, y_train)

LogisticRegression(max_iter=1000)

In [81]:
#make predictions
y_pred= log_model.predict(X_test_bow)

In [84]:
accuracy = accuracy_score(y_test, y_pred)
f1= f1_score(y_test, y_pred)

print('accuracy', accuracy)
print('f1 score',f1)

accuracy 0.8691136432388827
f1 score 0.8700180252353295